# Generated by Django 4.2.7 on 2024-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('addr_kk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('addr_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('addr_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('e_mail', models.CharField(blank=True, max_length=20, verbose_name='e-mail')),
                ('tel', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('priem_com', models.CharField(blank=True, max_length=20, verbose_name='Приёмная комиссия')),
                ('wats', models.CharField(blank=True, max_length=20, verbose_name='Watsapp')),
                ('workSchedule', models.CharField(blank=True, max_length=200, verbose_name='График работы')),
                ('workSchedule_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='График работы')),
                ('workSchedule_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='График работы')),
                ('workSchedule_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='График работы')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
