# Generated by Django 4.2.9 on 2024-01-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/educational-work/dormitory/documents', verbose_name='Файл')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/educational-work/dormitory/documents', verbose_name='Файл')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/educational-work/dormitory/documents', verbose_name='Файл')),
                ('file_en', models.FileField(null=True, upload_to='uploads/educational-work/dormitory/documents', verbose_name='Файл')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Общежитие Файлы',
                'verbose_name_plural': 'Общежитие Файлы',
            },
        ),
        migrations.CreateModel(
            name='DormitoryImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/educational-work/dormitory/images', verbose_name='Изображение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Общежитие Фото',
                'verbose_name_plural': 'Общежитие Фото',
            },
        ),
        migrations.CreateModel(
            name='GeneralInformationFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/educational-work/general-information/', verbose_name='Файл')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/educational-work/general-information/', verbose_name='Файл')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/educational-work/general-information/', verbose_name='Файл')),
                ('file_en', models.FileField(null=True, upload_to='uploads/educational-work/general-information/', verbose_name='Файл')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Общая информация',
                'verbose_name_plural': 'Общая информация',
            },
        ),
        migrations.CreateModel(
            name='PsychologicalServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/educational-work/psychological-service/', verbose_name='Файл')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/educational-work/psychological-service/', verbose_name='Файл')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/educational-work/psychological-service/', verbose_name='Файл')),
                ('file_en', models.FileField(null=True, upload_to='uploads/educational-work/psychological-service/', verbose_name='Файл')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Психологическая служба',
                'verbose_name_plural': 'Психологическая служба',
            },
        ),
        migrations.CreateModel(
            name='DormitoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('about_ru', models.TextField(blank=True, null=True)),
                ('about_kk', models.TextField(blank=True, null=True)),
                ('about_en', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(related_name='Файлы', to='educational_work.dormitoryfilesmodel')),
                ('images', models.ManyToManyField(related_name='Изображения', to='educational_work.dormitoryimagesmodel')),
            ],
            options={
                'verbose_name': 'Общежитие',
                'verbose_name_plural': 'Общежитие',
            },
        ),
        migrations.CreateModel(
            name='ClubsAndSectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('about', models.TextField(blank=True, default='', verbose_name='О кружке или секции')),
                ('about_ru', models.TextField(blank=True, default='', null=True, verbose_name='О кружке или секции')),
                ('about_kk', models.TextField(blank=True, default='', null=True, verbose_name='О кружке или секции')),
                ('about_en', models.TextField(blank=True, default='', null=True, verbose_name='О кружке или секции')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('teachers', models.ManyToManyField(blank=True, related_name='Преподаватели', to='staff.personmodel')),
            ],
            options={
                'verbose_name': ' Кружки и секции',
                'verbose_name_plural': ' Кружки и секции',
            },
        ),
        migrations.CreateModel(
            name='ClubsAndSectionsDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=400, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(blank=True, max_length=400, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=400, null=True, verbose_name='Название')),
                ('file', models.FileField(upload_to='uploads/educational-work/clubs-and-sections/', verbose_name='Файл')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='educational_work.clubsandsectionsmodel')),
            ],
            options={
                'verbose_name': 'Файлы кружков и секций',
                'verbose_name_plural': 'Файлы кружков и секций',
            },
        ),
    ]
