# Generated by Django 4.2.7 on 2023-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/educational-work/dormitory/documents', verbose_name='Файл')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Общежитие Файлы',
                'verbose_name_plural': 'Общежитие Файлы',
            },
        ),
        migrations.CreateModel(
            name='DormitoryImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/educational-work/dormitory/images', verbose_name='Изображение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Общежитие Фото',
                'verbose_name_plural': 'Общежитие Фото',
            },
        ),
        migrations.RemoveField(
            model_name='dormitorymodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='dormitorymodel',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='dormitorymodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dormitorymodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='dormitorymodel',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='dormitorymodel',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='dormitorymodel',
            name='documents',
            field=models.ManyToManyField(related_name='Файлы', to='educational_work.dormitoryfilesmodel'),
        ),
        migrations.AddField(
            model_name='dormitorymodel',
            name='images',
            field=models.ManyToManyField(related_name='Изображения', to='educational_work.dormitoryimagesmodel'),
        ),
    ]
