# Generated by Django 4.2.7 on 2023-12-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_work', '0002_alter_generalinformationfilesmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformationfilesmodel',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Статус файла'),
        ),
    ]
