# Generated by Django 4.2.7 on 2023-12-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_work', '0002_dormitoryfilesmodel_dormitoryimagesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitorymodel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dormitorymodel',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dormitorymodel',
            name='about_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dormitorymodel',
            name='about_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
