# Generated by Django 5.0.3 on 2024-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_work', '0003_youthpolicyfilesmodel_youthpolicyimagesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerrorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('video', models.FileField(upload_to='uploads/videos', verbose_name='Видео')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Информация о терроризме',
                'verbose_name_plural': 'Информация о терроризме',
            },
        ),
    ]
