# Generated by Django 4.2.7 on 2024-03-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_work', '0003_remove_dormitorymodel_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthPolicyFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/educational-work/youth-policy/documents', verbose_name='Файл')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/educational-work/youth-policy/documents', verbose_name='Файл')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/educational-work/youth-policy/documents', verbose_name='Файл')),
                ('file_en', models.FileField(null=True, upload_to='uploads/educational-work/youth-policy/documents', verbose_name='Файл')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Молодежная политика Файлы',
                'verbose_name_plural': 'Молодежная политика Файлы',
            },
        ),
        migrations.CreateModel(
            name='YouthPolicyImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/educational-work/youth-policy/images', verbose_name='Изображение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Молодежная политика Фото',
                'verbose_name_plural': 'Молодежная политика Фото',
            },
        ),
        migrations.CreateModel(
            name='YouthPolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('about_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('about_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('documents', models.ManyToManyField(blank=True, default=[], related_name='Файлы', to='educational_work.youthpolicyfilesmodel')),
                ('images', models.ManyToManyField(blank=True, default=[], related_name='Изображения', to='educational_work.youthpolicyimagesmodel')),
            ],
            options={
                'verbose_name': 'Молодежная политика',
                'verbose_name_plural': 'Молодежная политика',
            },
        ),
    ]
