# Generated by Django 4.2.7 on 2024-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_work', '0004_youthpolicyfilesmodel_youthpolicyimagesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicyimagesmodel',
            name='file_en',
            field=models.ImageField(null=True, upload_to='uploads/educational-work/youth-policy/images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='youthpolicyimagesmodel',
            name='file_kk',
            field=models.ImageField(null=True, upload_to='uploads/educational-work/youth-policy/images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='youthpolicyimagesmodel',
            name='file_ru',
            field=models.ImageField(null=True, upload_to='uploads/educational-work/youth-policy/images', verbose_name='Изображение'),
        ),
    ]
