# Generated by Django 5.0.3 on 2024-03-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_work', '0004_terrormodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrormodel',
            name='video',
            field=models.FileField(upload_to='uploads/educational-work/videos', verbose_name='Видео'),
        ),
    ]
