# Generated by Django 4.2.7 on 2024-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_work', '0005_alter_terrormodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicymodel',
            name='video',
            field=models.FileField(blank=True, upload_to='uploads/educational-work/youth-policy/videos', verbose_name='Видео'),
        ),
    ]
