# Generated by Django 4.2.2 on 2023-09-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Наименование категории')),
                ('category_name_ru', models.CharField(max_length=100, null=True, verbose_name='Наименование категории')),
                ('category_name_kk', models.CharField(max_length=100, null=True, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('news_title_ru', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('news_title_kk', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('news_img', models.ImageField(blank=True, upload_to='upload/news/%Y/%m/%d', verbose_name='Фото')),
                ('news_content', models.TextField(verbose_name='Контент')),
                ('news_content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('news_content_kk', models.TextField(null=True, verbose_name='Контент')),
                ('news_is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('news_is_achivment', models.BooleanField(default=False, verbose_name='Достижение')),
                ('news_create_date', models.DateTimeField(auto_now_add=True)),
                ('news_update_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.categorymodel', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
