# Generated by Django 5.0.1 on 2024-02-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='news_is_library',
            field=models.BooleanField(default=False, verbose_name='Библиотека'),
        ),
    ]
