# Generated by Django 4.2.7 on 2023-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='category_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='news_content_en',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='news_title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
