# Generated by Django 5.0.1 on 2024-02-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodel_news_is_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.categorymodel', verbose_name='Категория'),
        ),
    ]
