# Generated by Django 4.2.2 on 2023-09-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_cmcelmodel_cmcfizmodel_cmcitmodel_cmclangmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Название группы',
                'verbose_name_plural': 'Название группы',
            },
        ),
        migrations.AddField(
            model_name='cmcelmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='staff.group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='cmcfizmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='staff.group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='cmcitmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='staff.group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='cmclangmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='staff.group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='cmcobmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='staff.group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='depheadmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='staff.group', verbose_name='Группы'),
        ),
    ]
