# Generated by Django 4.2.7 on 2023-12-20 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_personmodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='position',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность'),
        ),
    ]
