# Generated by Django 4.2.7 on 2023-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_group_cmcelmodel_groups_cmcfizmodel_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmcelmodel',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='cmcfizmodel',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='cmcitmodel',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='cmclangmodel',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='cmcobmodel',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='depdirectormodel',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='depheadmodel',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='directormodel',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='positionmodel',
            name='position_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
    ]
