# Generated by Django 4.2.7 on 2024-03-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectors_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rectorsblogmaininfomodel',
            name='file',
        ),
        migrations.AddField(
            model_name='rectorsblogmaininfomodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/rectors-blog/info', verbose_name='Фото'),
        ),
    ]
