# Generated by Django 4.2.7 on 2024-03-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectors_blog', '0002_remove_rectorsblogmaininfomodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectorsblogmaininfomodel',
            name='cabinet',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='rectorsblogmaininfomodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='rectorsblogmaininfomodel',
            name='reception',
            field=models.CharField(blank=True, max_length=100, verbose_name='Приемная'),
        ),
    ]
