# Generated by Django 4.2.7 on 2024-03-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectors_blog', '0003_rectorsblogmaininfomodel_cabinet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectorsblogmaininfomodel',
            name='cabinet_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='rectorsblogmaininfomodel',
            name='cabinet_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='rectorsblogmaininfomodel',
            name='cabinet_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кабинет'),
        ),
    ]
