# Generated by Django 4.2.7 on 2024-03-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectors_blog', '0004_rectorsblogmaininfomodel_cabinet_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectorsblogmaininfomodel',
            name='info',
            field=models.TextField(blank=True, verbose_name='Приветсвие'),
        ),
        migrations.AlterField(
            model_name='rectorsblogmaininfomodel',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Приветсвие'),
        ),
        migrations.AlterField(
            model_name='rectorsblogmaininfomodel',
            name='info_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Приветсвие'),
        ),
        migrations.AlterField(
            model_name='rectorsblogmaininfomodel',
            name='info_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Приветсвие'),
        ),
    ]
