# Generated by Django 4.2.7 on 2024-03-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectors_blog', '0005_alter_rectorsblogmaininfomodel_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectorsblogquestionanswermodel',
            name='answer',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='rectorsblogquestionanswermodel',
            name='question',
            field=models.CharField(blank=True, max_length=800, verbose_name='Вопрос'),
        ),
    ]
