# Generated by Django 4.2.7 on 2024-03-21 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectors_blog', '0006_alter_rectorsblogquestionanswermodel_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectorsblogquestionanswermodel',
            name='email',
            field=models.EmailField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='rectorsblogquestionanswermodel',
            name='firstName',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='rectorsblogquestionanswermodel',
            name='lastName',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='rectorsblogquestionanswermodel',
            name='question',
            field=models.CharField(max_length=800, validators=[django.core.validators.MinLengthValidator(25)], verbose_name='Вопрос'),
        ),
    ]
