# Generated by Django 4.2.7 on 2023-12-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOfTrusteesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='uploads/Docs', verbose_name='Документ')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Документ для попечительского совета',
                'verbose_name_plural': 'Документ для попечительского совета',
            },
        ),
        migrations.CreateModel(
            name='CollegeDocsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_license', models.FileField(upload_to='uploads/Docs', verbose_name='Лицензия')),
                ('college_reg', models.FileField(upload_to='uploads/Docs', verbose_name='Устав')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Документы колледжа',
                'verbose_name_plural': 'Документы колледжа',
            },
        ),
        migrations.CreateModel(
            name='CollegeHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Дата события')),
                ('info', models.TextField(verbose_name='Описание')),
                ('info_ru', models.TextField(null=True, verbose_name='Описание')),
                ('info_kk', models.TextField(null=True, verbose_name='Описание')),
                ('info_en', models.TextField(null=True, verbose_name='Описание')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'История колледжа',
                'verbose_name_plural': 'История колледжа',
            },
        ),
        migrations.CreateModel(
            name='IndustrialCouncilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='uploads/Docs', verbose_name='Документ')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Документ для индустриального совета',
                'verbose_name_plural': 'Документ для индустриального совета',
            },
        ),
        migrations.CreateModel(
            name='PedagogicalCouncilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='uploads/Docs', verbose_name='Документ')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Документ для педагогического совета',
                'verbose_name_plural': 'Документ для педагогического совета',
            },
        ),
    ]
