# Generated by Django 4.2.9 on 2024-01-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOfTrusteesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='uploads/about-college/board-of-trustees', verbose_name='Документ')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/about-college/board-of-trustees', verbose_name='Документ')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/about-college/board-of-trustees', verbose_name='Документ')),
                ('file_en', models.FileField(null=True, upload_to='uploads/about-college/board-of-trustees', verbose_name='Документ')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Документ для попечительского совета',
                'verbose_name_plural': 'Документ для попечительского совета',
            },
        ),
        migrations.CreateModel(
            name='CollegeDocsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_license', models.FileField(blank=True, null=True, upload_to='uploads/Docs', verbose_name='Лицензия')),
                ('college_license_ru', models.FileField(blank=True, null=True, upload_to='uploads/Docs', verbose_name='Лицензия')),
                ('college_license_kk', models.FileField(blank=True, null=True, upload_to='uploads/Docs', verbose_name='Лицензия')),
                ('college_license_en', models.FileField(blank=True, null=True, upload_to='uploads/Docs', verbose_name='Лицензия')),
                ('college_reg', models.FileField(blank=True, null=True, upload_to='uploads/about-college/docs', verbose_name='Устав')),
                ('college_reg_ru', models.FileField(blank=True, null=True, upload_to='uploads/about-college/docs', verbose_name='Устав')),
                ('college_reg_kk', models.FileField(blank=True, null=True, upload_to='uploads/about-college/docs', verbose_name='Устав')),
                ('college_reg_en', models.FileField(blank=True, null=True, upload_to='uploads/about-college/docs', verbose_name='Устав')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Документы колледжа',
                'verbose_name_plural': 'Документы колледжа',
            },
        ),
        migrations.CreateModel(
            name='CollegeHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Дата события')),
                ('info', models.TextField(verbose_name='Описание')),
                ('info_ru', models.TextField(null=True, verbose_name='Описание')),
                ('info_kk', models.TextField(null=True, verbose_name='Описание')),
                ('info_en', models.TextField(null=True, verbose_name='Описание')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'История колледжа',
                'verbose_name_plural': 'История колледжа',
            },
        ),
        migrations.CreateModel(
            name='IndustrialCouncilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='uploads/about-college/industrial-council', verbose_name='Документ')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/about-college/industrial-council', verbose_name='Документ')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/about-college/industrial-council', verbose_name='Документ')),
                ('file_en', models.FileField(null=True, upload_to='uploads/about-college/industrial-council', verbose_name='Документ')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Документ для индустриального совета',
                'verbose_name_plural': 'Документ для индустриального совета',
            },
        ),
        migrations.CreateModel(
            name='PedagogicalCouncilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='uploads/about-college/pedagogical-council', verbose_name='Документ')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/about-college/pedagogical-council', verbose_name='Документ')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/about-college/pedagogical-council', verbose_name='Документ')),
                ('file_en', models.FileField(null=True, upload_to='uploads/about-college/pedagogical-council', verbose_name='Документ')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Документ для педагогического совета',
                'verbose_name_plural': 'Документ для педагогического совета',
            },
        ),
        migrations.CreateModel(
            name='SpecInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=200, verbose_name='Специальность')),
                ('spec_name_ru', models.CharField(max_length=200, null=True, verbose_name='Специальность')),
                ('spec_name_kk', models.CharField(max_length=200, null=True, verbose_name='Специальность')),
                ('spec_name_en', models.CharField(max_length=200, null=True, verbose_name='Специальность')),
                ('spec_info', models.TextField(verbose_name='Описание')),
                ('spec_info_ru', models.TextField(null=True, verbose_name='Описание')),
                ('spec_info_kk', models.TextField(null=True, verbose_name='Описание')),
                ('spec_info_en', models.TextField(null=True, verbose_name='Описание')),
                ('spec_img', models.ImageField(blank=True, upload_to='uploads/about-college/specs', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Специальности',
                'verbose_name_plural': 'Специальности',
            },
        ),
    ]
