    # Generated by Django 4.2.9 on 2024-01-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeTextHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'История колледжа(текст)',
                'verbose_name_plural': 'История колледжа(текст)',
            },
        ),
        migrations.AlterModelOptions(
            name='collegehistorymodel',
            options={'verbose_name': 'История колледжа(события)', 'verbose_name_plural': 'История колледжа(события)'},
        ),
        migrations.AlterField(
            model_name='collegehistorymodel',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
