# Generated by Django 5.0.1 on 2024-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_college', '0002_collegetexthistorymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Наименование изображения')),
                ('title_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование изображения')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование изображения')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование изображения')),
                ('image', models.ImageField(upload_to='uploads/about-college/gallery', verbose_name='Изображение')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
