# Generated by Django 4.2.7 on 2024-03-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_college', '0003_gallerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegetexthistorymodel',
            name='our_mission',
            field=models.TextField(blank=True, verbose_name='Наша миссия'),
        ),
    ]
