# Generated by Django 4.2.7 on 2024-03-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_college', '0005_collegetexthistorymodel_our_mission_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedocsmodel',
            name='accreditation',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Docs/accreditation', verbose_name='Аккредитация'),
        ),
        migrations.AddField(
            model_name='collegedocsmodel',
            name='accreditation_en',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Docs/accreditation', verbose_name='Аккредитация'),
        ),
        migrations.AddField(
            model_name='collegedocsmodel',
            name='accreditation_kk',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Docs/accreditation', verbose_name='Аккредитация'),
        ),
        migrations.AddField(
            model_name='collegedocsmodel',
            name='accreditation_ru',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Docs/accreditation', verbose_name='Аккредитация'),
        ),
    ]
