# Generated by Django 4.2.7 on 2023-12-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetentionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование компетенции')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Наименование компетенции')),
                ('title_kk', models.CharField(max_length=100, null=True, verbose_name='Наименование компетенции')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Наименование компетенции')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание компетенции')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='Описание компетенции')),
                ('description_kk', models.TextField(blank=True, default='', null=True, verbose_name='Описание компетенции')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Описание компетенции')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенция',
            },
        ),
        migrations.CreateModel(
            name='RuleWorldSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, upload_to='uploads/worldskills/rules/', verbose_name='Файл 1')),
                ('file2', models.FileField(blank=True, upload_to='uploads/worldskills/rules/', verbose_name='Файл 2')),
                ('file3', models.FileField(blank=True, upload_to='uploads/worldskills/rules/', verbose_name='Файл 3')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правила проведения WorldSkills',
                'verbose_name_plural': 'Правила проведения WorldSkills',
            },
        ),
        migrations.CreateModel(
            name='CompetentionDocumentationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='uploads/worldskills/documentations/', verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('competention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Компетенция', to='worldskills.competentionmodel')),
            ],
            options={
                'verbose_name': 'Документация к компетенции',
                'verbose_name_plural': 'Документация к компетенции',
            },
        ),
    ]
