# Generated by Django 4.2.7 on 2023-12-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldskills', '0002_remove_competentionmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competentiondocumentationmodel',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
