# Generated by Django 4.2.9 on 2024-01-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegePartnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('partner_name_ru', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('partner_name_kk', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('partner_name_en', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('partner_logo', models.ImageField(blank=True, upload_to='uploads/index-page/partners', verbose_name='Лого')),
                ('partner_url', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Партнёры колледжа',
                'verbose_name_plural': 'Партнёры колледжа',
            },
        ),
        migrations.CreateModel(
            name='CollegeSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Заголовок')),
                ('number_ru', models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок')),
                ('number_kk', models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок')),
                ('number_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='uploads/slider', verbose_name='Изображение')),
                ('image2', models.ImageField(blank=True, upload_to='uploads/slider', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, upload_to='uploads/slider', verbose_name='Изображение 3')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Слайдер на главной странице',
                'verbose_name_plural': 'Слайдер на главной странице',
            },
        ),
        migrations.CreateModel(
            name='NewSocialMediaLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на сайт')),
                ('icon_file', models.FileField(blank=True, upload_to='uploads/socialMedias', verbose_name='Загрузить иконку')),
                ('icon_link', models.URLField(blank=True, verbose_name='Ссылка на иконку')),
                ('public', models.BooleanField(blank=True, default=False, verbose_name='Опубликовать')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Новая социальная сеть',
                'verbose_name_plural': 'Новая социальная сеть',
            },
        ),
        migrations.CreateModel(
            name='SliderForDocumentListSlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/main/documents-slider/slides/', verbose_name='Слайд')),
                ('image_ru', models.ImageField(null=True, upload_to='uploads/main/documents-slider/slides/', verbose_name='Слайд')),
                ('image_kk', models.ImageField(null=True, upload_to='uploads/main/documents-slider/slides/', verbose_name='Слайд')),
                ('image_en', models.ImageField(null=True, upload_to='uploads/main/documents-slider/slides/', verbose_name='Слайд')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Слайд для слайдера для страниц с документами',
                'verbose_name_plural': 'Слайд для слайдера для страниц с документами',
            },
        ),
        migrations.CreateModel(
            name='ThemesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gray_theme', models.BooleanField(default=False, verbose_name='Серая тема')),
            ],
            options={
                'verbose_name': 'Расцветка сайта',
                'verbose_name_plural': 'Расцветка сайта',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, verbose_name='Ссылка Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Ссылка Facebook')),
                ('youtube', models.URLField(blank=True, verbose_name='Ссылка YouTube')),
                ('telegram', models.URLField(blank=True, verbose_name='Ссылка Telegram')),
                ('tiktok', models.URLField(blank=True, verbose_name='Ссылка TikTok')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('other_medias', models.ManyToManyField(blank=True, default=[], to='main.newsocialmedialinkmodel')),
            ],
            options={
                'verbose_name': 'Ссылки на социальные сети',
                'verbose_name_plural': 'Ссылки на социальные сети',
            },
        ),
        migrations.CreateModel(
            name='SliderForDocumentListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('Общая информация', 'Общая информация'), ('Кружки и секции', 'Кружки и секции'), ('Психологическая служба', 'Психологическая служба'), ('Противодействие коррупции', 'Противодействие коррупции'), ('Программа полиязычия', 'Программа полиязычия')], max_length=100, verbose_name='Страница')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, default=[], to='main.sliderfordocumentlistslidemodel', verbose_name='Слайды')),
            ],
            options={
                'verbose_name': 'Слайдер для страниц с документами',
                'verbose_name_plural': 'Слайдер для страниц с документами',
            },
        ),
    ]
