# Generated by Django 5.0.1 on 2024-02-08 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeslidermodel',
            options={'verbose_name': 'Слайд слайдера на главной странице', 'verbose_name_plural': 'Слайд слайдера на главной странице'},
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='image2',
        ),
        migrations.CreateModel(
            name='CollegeSliderImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/slider/', verbose_name='Изображение')),
                ('status_1', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('status_2', models.BooleanField(default=False, verbose_name='Второе изображение')),
                ('status_3', models.BooleanField(default=False, verbose_name='Третье изображение')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('college_slider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.collegeslidermodel', verbose_name='Слад')),
            ],
            options={
                'verbose_name': 'Изображение слайдера на главной странице',
                'verbose_name_plural': 'Изображение слайдера на главной странице',
            },
        ),
    ]
