# Generated by Django 4.2.9 on 2024-02-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeslidermodel',
            options={'verbose_name': 'Cлайдер на главной странице', 'verbose_name_plural': 'Cлайдер на главной странице'},
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='number',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='number_en',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='number_kk',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='number_ru',
        ),
        migrations.AlterField(
            model_name='collegeslidermodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='collegeslidermodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='collegeslidermodel',
            name='title_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='collegeslidermodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sliderfordocumentlistmodel',
            name='page',
            field=models.CharField(choices=[('Общая информация', 'Общая информация'), ('Кружки и секции', 'Кружки и секции'), ('Психологическая служба', 'Психологическая служба'), ('Противодействие коррупции', 'Противодействие коррупции'), ('Программа полиязычия', 'Программа полиязычия'), ('Попечительский совет', 'Попечительский совет'), ('Педагогический совет', 'Педагогический совет'), ('Индустриальный совет', 'Индустриальный совет')], max_length=100, verbose_name='Страница'),
        ),
        migrations.CreateModel(
            name='CollegeSliderImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/slider/', verbose_name='Изображение')),
                ('status_1', models.BooleanField(default=False, verbose_name='Отметить как главное изображение')),
                ('status_2', models.BooleanField(default=False, verbose_name='Отметить как второе изображение')),
                ('status_3', models.BooleanField(default=False, verbose_name='Отметить как третье изображение')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('college_slider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.collegeslidermodel', verbose_name='Слад')),
            ],
            options={
                'verbose_name': 'Изображение слайдера на главной странице',
                'verbose_name_plural': 'Изображение слайдера на главной странице',
            },
        ),
    ]
