# Generated by Django 4.2.9 on 2024-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_collegeslidermodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroLogosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(blank=True, max_length=50, null=True)),
                ('years_kk', models.CharField(blank=True, max_length=50, null=True)),
                ('years_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('years_en', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/index-page/logos')),
                ('image_kk', models.ImageField(blank=True, null=True, upload_to='uploads/index-page/logos')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='uploads/index-page/logos')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='uploads/index-page/logos')),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('text_kk', models.CharField(blank=True, max_length=250, null=True)),
                ('text_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('text_en', models.CharField(blank=True, max_length=250, null=True)),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Логотипы и надписи на главной странице',
                'verbose_name_plural': 'Логотипы и надписи на главной странице',
            },
        ),
        migrations.AlterField(
            model_name='collegesliderimagemodel',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='collegeslidermodel',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
