# Generated by Django 5.0.1 on 2024-02-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_collegeslidermodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='image3',
        ),
    ]
