# Generated by Django 5.0.1 on 2024-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_collegeslidermodel_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='number',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='number_en',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='number_kk',
        ),
        migrations.RemoveField(
            model_name='collegeslidermodel',
            name='number_ru',
        ),
        migrations.AlterField(
            model_name='collegeslidermodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='collegeslidermodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='collegeslidermodel',
            name='title_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='collegeslidermodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
