# Generated by Django 5.0.1 on 2024-02-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_collegeslidermodel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderfordocumentlistmodel',
            name='page',
            field=models.CharField(choices=[('Общая информация', 'Общая информация'), ('Кружки и секции', 'Кружки и секции'), ('Психологическая служба', 'Психологическая служба'), ('Противодействие коррупции', 'Противодействие коррупции'), ('Программа полиязычия', 'Программа полиязычия'), ('Попечительский совет', 'Попечительский совет'), ('Педагогический совет', 'Педагогический совет'), ('Индустриальный совет', 'Индустриальный совет')], max_length=100, verbose_name='Страница'),
        ),
    ]
