# Generated by Django 4.2.2 on 2023-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_academicprocessschedulemodel_callpairschedulemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callpairschedulemodel',
            name='pair_schedule',
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='pair_schedule_1',
            field=models.FileField(blank=True, upload_to='uploads/schedule', verbose_name='Расписание пар 1 курс'),
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='pair_schedule_2',
            field=models.FileField(blank=True, upload_to='uploads/schedule', verbose_name='Расписание пар 2 курс'),
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='pair_schedule_3',
            field=models.FileField(blank=True, upload_to='uploads/schedule', verbose_name='Расписание пар 3 курс'),
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='pair_schedule_4',
            field=models.FileField(blank=True, upload_to='uploads/schedule', verbose_name='Расписание пар 4 курс'),
        ),
    ]
