# Generated by Django 4.2.2 on 2023-09-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_studenteventmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callpairschedulemodel',
            old_name='pair_schedule_1',
            new_name='course_1_schedule',
        ),
        migrations.RenameField(
            model_name='callpairschedulemodel',
            old_name='pair_schedule_2',
            new_name='course_2_schedule',
        ),
        migrations.RenameField(
            model_name='callpairschedulemodel',
            old_name='pair_schedule_3',
            new_name='course_3_schedule',
        ),
        migrations.RenameField(
            model_name='callpairschedulemodel',
            old_name='pair_schedule_4',
            new_name='course_4_schedule',
        ),
        migrations.RemoveField(
            model_name='callpairschedulemodel',
            name='call_schedule',
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='call_schedule_1_pair',
            field=models.CharField(default='', max_length=20, verbose_name='1 пара'),
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='call_schedule_2_pair',
            field=models.CharField(default='', max_length=20, verbose_name='2 пара'),
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='call_schedule_3_pair',
            field=models.CharField(default='', max_length=20, verbose_name='3 пара'),
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='call_schedule_4_pair',
            field=models.CharField(default='', max_length=20, verbose_name='4 пара'),
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='call_schedule_5_pair',
            field=models.CharField(default='', max_length=20, verbose_name='5 пара'),
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='call_schedule_6_pair',
            field=models.CharField(default='', max_length=20, verbose_name='6 пара'),
        ),
        migrations.AddField(
            model_name='callpairschedulemodel',
            name='call_schedule_7_pair',
            field=models.CharField(default='', max_length=20, verbose_name='7 пара'),
        ),
    ]
