# Generated by Django 4.2.7 on 2023-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_pair_schedule_1_callpairschedulemodel_course_1_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegecontactmodel',
            name='addr_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='collegehistorymodel',
            name='info_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='collegepartnersmodel',
            name='partner_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='statesymbolsmodel',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='statesymbolsmodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
