# Generated by Django 4.2.7 on 2023-11-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_collegecontactmodel_addr_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteventmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/events', verbose_name='Изображение'),
        ),
    ]
