# Generated by Django 4.2.7 on 2023-11-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_studenteventmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteventmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='studenteventmodel',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='studenteventmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='studenteventmodel',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='studenteventmodel',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='studenteventmodel',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
    ]
