# Generated by Django 4.2.7 on 2023-12-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_studenteventmodel_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodicRecomendationsCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименования')),
                ('is_for_student', models.BooleanField(default=False, verbose_name='Это для студентов')),
                ('is_for_teacher', models.BooleanField(default=False, verbose_name='Это для преподавателей')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'График Учебного процесса',
                'verbose_name_plural': 'График Учебного процесса',
            },
        ),
        migrations.CreateModel(
            name='MetodicRecomendationsDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='Наименование')),
                ('file', models.FileField(upload_to='uploads/metodic_recomendations/', verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='main.metodicrecomendationscategorymodel')),
            ],
        ),
    ]
