# Generated by Django 4.2.7 on 2023-12-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_metodicrecomendationscategorymodel_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodicrecomendationscategorymodel',
            options={'verbose_name': 'Категории методических рекомендаций', 'verbose_name_plural': 'Категории методических рекомендаций'},
        ),
        migrations.AlterModelOptions(
            name='metodicrecomendationsdocumentmodel',
            options={'verbose_name': 'Файлы методических рекомендаций', 'verbose_name_plural': 'Файлы методических рекомендаций'},
        ),
    ]
