# Generated by Django 4.2.7 on 2023-12-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_metodicrecomendationscategorymodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeDocsModel',
        ),
        migrations.DeleteModel(
            name='CollegeHistoryModel',
        ),
    ]
