# Generated by Django 4.2.7 on 2023-12-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_collegedocsmodel_delete_collegehistorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateSymbolsModel',
        ),
    ]
