# Generated by Django 4.2.7 on 2023-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_statesymbolsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicProcessScheduleModel',
        ),
        migrations.DeleteModel(
            name='CallPairScheduleModel',
        ),
        migrations.DeleteModel(
            name='CollegeContactModel',
        ),
        migrations.RemoveField(
            model_name='metodicrecomendationsdocumentmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='StudentEventModel',
        ),
        migrations.AlterField(
            model_name='collegepartnersmodel',
            name='partner_logo',
            field=models.ImageField(blank=True, upload_to='uploads/index-page/partners', verbose_name='Лого'),
        ),
        migrations.DeleteModel(
            name='MetodicRecomendationsCategoryModel',
        ),
        migrations.DeleteModel(
            name='MetodicRecomendationsDocumentModel',
        ),
    ]
