# Generated by Django 4.2.7 on 2023-12-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_academicprocessschedulemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Заголовок')),
                ('number_ru', models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок')),
                ('number_kk', models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок')),
                ('number_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='uploads/slider', verbose_name='Изображение')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Партнёры колледжа',
                'verbose_name_plural': 'Партнёры колледжа',
            },
        ),
    ]
