# Generated by Django 4.2.7 on 2023-12-19 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProcessScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='uploads/information/year-schedule', verbose_name='График Учебного процесса')),
            ],
            options={
                'verbose_name': 'График Учебного процесса',
                'verbose_name_plural': 'График Учебного процесса',
            },
        ),
        migrations.CreateModel(
            name='CallPairScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_schedule_1_pair', models.CharField(default='', max_length=20, verbose_name='1 пара')),
                ('call_schedule_2_pair', models.CharField(default='', max_length=20, verbose_name='2 пара')),
                ('call_schedule_3_pair', models.CharField(default='', max_length=20, verbose_name='3 пара')),
                ('call_schedule_4_pair', models.CharField(default='', max_length=20, verbose_name='4 пара')),
                ('call_schedule_5_pair', models.CharField(default='', max_length=20, verbose_name='5 пара')),
                ('call_schedule_6_pair', models.CharField(default='', max_length=20, verbose_name='6 пара')),
                ('call_schedule_7_pair', models.CharField(default='', max_length=20, verbose_name='7 пара')),
                ('course_1_schedule', models.FileField(blank=True, upload_to='uploads/information/schedule', verbose_name='Расписание пар 1 курс')),
                ('course_2_schedule', models.FileField(blank=True, upload_to='uploads/information/schedule', verbose_name='Расписание пар 2 курс')),
                ('course_3_schedule', models.FileField(blank=True, upload_to='uploads/information/schedule', verbose_name='Расписание пар 3 курс')),
                ('course_4_schedule', models.FileField(blank=True, upload_to='uploads/information/schedule', verbose_name='Расписание пар 4 курс')),
            ],
            options={
                'verbose_name': 'Расписание звонков и расписание пар',
                'verbose_name_plural': 'Расписание звонков и расписание пар',
            },
        ),
        migrations.CreateModel(
            name='CollegeContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=300, verbose_name='Адрес')),
                ('addr_ru', models.CharField(max_length=300, null=True, verbose_name='Адрес')),
                ('addr_kk', models.CharField(max_length=300, null=True, verbose_name='Адрес')),
                ('addr_en', models.CharField(max_length=300, null=True, verbose_name='Адрес')),
                ('e_mail', models.CharField(max_length=20, verbose_name='e-mail')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('priem_com', models.CharField(max_length=20, verbose_name='Приёмная комиссия')),
                ('wats', models.CharField(max_length=20, verbose_name='Watsapp')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/information/financial-statements/', verbose_name='Файл')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Финансовая отчетность',
                'verbose_name_plural': 'Финансовая отчетность',
            },
        ),
        migrations.CreateModel(
            name='MetodicRecomendationsCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('is_for_student', models.BooleanField(default=False, verbose_name='Это для студентов')),
                ('is_for_teacher', models.BooleanField(default=False, verbose_name='Это для преподавателей')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категории методических рекомендаций',
                'verbose_name_plural': 'Категории методических рекомендаций',
            },
        ),
        migrations.CreateModel(
            name='StudentEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='uploads/information/student/events', verbose_name='Изображение')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Дата конца')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'События для студента',
                'verbose_name_plural': 'События для студента',
            },
        ),
        migrations.CreateModel(
            name='MetodicRecomendationsDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='Наименование')),
                ('title_ru', models.CharField(blank=True, max_length=400, null=True, verbose_name='Наименование')),
                ('title_kk', models.CharField(blank=True, max_length=400, null=True, verbose_name='Наименование')),
                ('title_en', models.CharField(blank=True, max_length=400, null=True, verbose_name='Наименование')),
                ('file', models.FileField(upload_to='uploads/information/metodic-recomendations/', verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='information.metodicrecomendationscategorymodel')),
            ],
            options={
                'verbose_name': 'Файлы методических рекомендаций',
                'verbose_name_plural': 'Файлы методических рекомендаций',
            },
        ),
    ]
