# Generated by Django 5.0.1 on 2024-02-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название файла')),
                ('title_kk', models.CharField(max_length=250, null=True, verbose_name='Название файла')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='Название файла')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/information/library/files', verbose_name='Файл')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/information/library/files', verbose_name='Файл')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/information/library/files', verbose_name='Файл')),
                ('file_en', models.FileField(null=True, upload_to='uploads/information/library/files', verbose_name='Файл')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Библиотека, файлы',
                'verbose_name_plural': 'Библиотека, файлы',
            },
        ),
        migrations.CreateModel(
            name='LibrarySliderImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/information/library/slider', verbose_name='Изображение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Библиотека, изображения для слайдера',
                'verbose_name_plural': 'Библиотека, изображения для слайдера',
            },
        ),
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slider_files', models.ManyToManyField(blank=True, default=None, to='information.libraryfilesmodel', verbose_name='Файлы')),
                ('slider_images', models.ManyToManyField(blank=True, default=None, to='information.librarysliderimagemodel', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Библиотека',
                'verbose_name_plural': 'Библиотека',
            },
        ),
    ]
