# Generated by Django 4.2.7 on 2023-12-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDocsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название документа')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Название документа')),
                ('title_kk', models.CharField(max_length=500, null=True, verbose_name='Название документа')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Название документа')),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Необходимые Документы',
                'verbose_name_plural': 'Необходимые Документы',
            },
        ),
    ]
