# Generated by Django 4.2.7 on 2024-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_libraryfilesmodel_librarysliderimagemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryContactsEmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Email общежития',
                'verbose_name_plural': 'Email общежития',
            },
        ),
        migrations.CreateModel(
            name='DormitoryContactsPhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Телефон общежития',
                'verbose_name_plural': 'Телефон общежития',
            },
        ),
        migrations.CreateModel(
            name='DormitoryFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/educational-work/dormitory/documents', verbose_name='Файл')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/educational-work/dormitory/documents', verbose_name='Файл')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/educational-work/dormitory/documents', verbose_name='Файл')),
                ('file_en', models.FileField(null=True, upload_to='uploads/educational-work/dormitory/documents', verbose_name='Файл')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Общежитие Файлы',
                'verbose_name_plural': 'Общежитие Файлы',
            },
        ),
        migrations.CreateModel(
            name='DormitoryImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/educational-work/dormitory/images', verbose_name='Изображение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Общежитие Фото',
                'verbose_name_plural': 'Общежитие Фото',
            },
        ),
        migrations.CreateModel(
            name='DormitoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('about_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('about_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('contact_email', models.ManyToManyField(blank=True, default=[], to='information.dormitorycontactsemailmodel', verbose_name='Почты')),
                ('contact_phone', models.ManyToManyField(blank=True, default=[], to='information.dormitorycontactsphonemodel', verbose_name='Телефоны')),
                ('documents', models.ManyToManyField(related_name='Файлы', to='information.dormitoryfilesmodel')),
                ('images', models.ManyToManyField(related_name='Изображения', to='information.dormitoryimagesmodel')),
            ],
            options={
                'verbose_name': 'Общежитие',
                'verbose_name_plural': 'Общежитие',
            },
        ),
    ]
