# Generated by Django 4.2.7 on 2024-03-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_ourunionfilesmodel_ourunionimagesmodel_ourunionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitorymodel',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AddField(
            model_name='ourunionmodel',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
