# Generated by Django 4.2.7 on 2024-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_dormitorymodel_is_public_ourunionmodel_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitoryimagesmodel',
            name='file_en',
            field=models.ImageField(null=True, upload_to='uploads/educational-work/dormitory/images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='dormitoryimagesmodel',
            name='file_kk',
            field=models.ImageField(null=True, upload_to='uploads/educational-work/dormitory/images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='dormitoryimagesmodel',
            name='file_ru',
            field=models.ImageField(null=True, upload_to='uploads/educational-work/dormitory/images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='ourunionimagesmodel',
            name='file_en',
            field=models.ImageField(null=True, upload_to='uploads/information/our-union/images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='ourunionimagesmodel',
            name='file_kk',
            field=models.ImageField(null=True, upload_to='uploads/information/our-union/images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='ourunionimagesmodel',
            name='file_ru',
            field=models.ImageField(null=True, upload_to='uploads/information/our-union/images', verbose_name='Изображение'),
        ),
    ]
