# Generated by Django 4.2.7 on 2024-03-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_dormitoryimagesmodel_file_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeContactModel',
        ),
    ]
