# Generated by Django 4.2.7 on 2024-03-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_dormitorymodel_video_en_dormitorymodel_video_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitorymodel',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='dormitorymodel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='librarymodel',
            name='slider_files',
        ),
        migrations.RemoveField(
            model_name='librarymodel',
            name='slider_images',
        ),
        migrations.RemoveField(
            model_name='ourunionmodel',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='ourunionmodel',
            name='images',
        ),
    ]
