# Generated by Django 4.2.7 on 2023-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0002_specinfomodel_spec_info_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specinfomodel',
            name='spec_info_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='specinfomodel',
            name='spec_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Специальность'),
        ),
    ]
