# Generated by Django 4.2.9 on 2024-01-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCorruptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='uploads/state/anti-corruption/', verbose_name='Документ')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/state/anti-corruption/', verbose_name='Документ')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/state/anti-corruption/', verbose_name='Документ')),
                ('file_en', models.FileField(null=True, upload_to='uploads/state/anti-corruption/', verbose_name='Документ')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Противодействие коррупции',
                'verbose_name_plural': 'Противодействие коррупции',
            },
        ),
        migrations.CreateModel(
            name='PolyiyasiaProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='uploads/state/polyiyasia-program/', verbose_name='Документ')),
                ('file_ru', models.FileField(null=True, upload_to='uploads/state/polyiyasia-program/', verbose_name='Документ')),
                ('file_kk', models.FileField(null=True, upload_to='uploads/state/polyiyasia-program/', verbose_name='Документ')),
                ('file_en', models.FileField(null=True, upload_to='uploads/state/polyiyasia-program/', verbose_name='Документ')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Документ программы полиязычия',
                'verbose_name_plural': 'Документ программы полиязычия',
            },
        ),
        migrations.CreateModel(
            name='PresidentialMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=500, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.FileField(blank=True, upload_to='uploads/state/presidential-message/', verbose_name='Изображение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Послание президента',
                'verbose_name_plural': 'Послание президента',
            },
        ),
        migrations.CreateModel(
            name='StateServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='uploads/state/state-services/', verbose_name='Документ')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Документ государственных услуг',
                'verbose_name_plural': 'Документ государственных услуг',
            },
        ),
        migrations.CreateModel(
            name='StateSymbolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='upload/state-symbols/', verbose_name='Изображение')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('desc_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('desc_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('desc_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Государственные Символы',
                'verbose_name_plural': 'Государственные Символы',
            },
        ),
    ]
