# Generated by Django 4.2.7 on 2023-12-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCorruptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=250, verbose_name='Заголовок для 1 файла')),
                ('title1_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок для 1 файла')),
                ('title1_kk', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок для 1 файла')),
                ('title1_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок для 1 файла')),
                ('file1', models.FileField(blank=True, upload_to='uploads/state/anti-corruption/', verbose_name='Файл 1')),
                ('title2', models.CharField(blank=True, max_length=250, verbose_name='Заголовок для 2 файла')),
                ('title2_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок для 2 файла')),
                ('title2_kk', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок для 2 файла')),
                ('title2_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок для 2 файла')),
                ('file2', models.FileField(blank=True, upload_to='uploads/state/anti-corruption/', verbose_name='Файл 2')),
                ('title3', models.CharField(blank=True, max_length=250, verbose_name='Заголовок для 3 файла')),
                ('title3_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок для 3 файла')),
                ('title3_kk', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок для 3 файла')),
                ('title3_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок для 3 файла')),
                ('file3', models.FileField(blank=True, upload_to='uploads/state/anti-corruption    /', verbose_name='Файл 3')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Противодействие коррупции',
                'verbose_name_plural': 'Противодействие коррупции',
            },
        ),
    ]
