# Generated by Django 4.2.7 on 2023-12-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticorruptionmodel',
            name='file3',
            field=models.FileField(blank=True, upload_to='uploads/state/anti-corruption/', verbose_name='Файл 3'),
        ),
    ]
